FROM centos:7
MAINTAINER Jawed khelil
LABEL git.version=@VERSION@
USER root
# Update all the packages
RUN yum -y upgrade && yum clean all
RUN yum -y install epel-release
RUN yum -y install python-pip && \
    yum clean all 
COPY hello /hello
RUN pip install -r /hello/requirements.txt
#USER 1000
WORKDIR /hello
ENTRYPOINT ["/hello/server.py"]
